services:
  - type: web
    name: stu-selection-render
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    runtime: python
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
